---

- name: Test distribution
  assert:
    that: >
      ansible_os_family == "RedHat" or
      ansible_os_family == "Debian"

- include: package.yaml

- name: Set OS dependent variables
  include_vars: "{{ item }}"
  when: sudo_defaults is not defined and sudo_users is not defined
  with_first_found:
   - "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
   - "{{ ansible_distribution }}.yml"
   - "{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.yml"
   - "{{ ansible_os_family }}.yml"
   - default.yml
  tags:
    - always

- name: Create /etc/sudoers file
  template:
    src: sudoers.j2
    dest: /etc/sudoers
    owner: root
    group: root
    mode: 0440
    validate: "{{ sudo_visudo }} -cf %s"
  tags:
    - sudo_config
